Models/ErrorViewModel.cs
namespace _4d_dotnet.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/WeatherModel.cs
public class WeatherModel {
    public TimeOnly MeasurementTime { get; set; }
    public List<WeatherInstance> Instances { get; set; }
}

public record WeatherInstance(string City, double Temperature, string Weather);

Models/WeatherRequestModel.cs
public record WeatherRequestModel(string City, List<WeatherRequestInstance> Instances);

public record WeatherRequestInstance(string Day, decimal Temperature, string Weather);

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using _4d_dotnet.Models;

namespace _4d_dotnet.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/RestController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using _4d_dotnet.Models;
using Microsoft.AspNetCore.Authorization.Infrastructure;
using NuGet.Common;

namespace _4d_dotnet.Controllers;

[Route("[controller]")]
public class RestController : ControllerBase
{

    [HttpGet]
    public IActionResult Index()
    {
        return Ok(DateTime.Now);
    }
}

Controllers/WeatherController.cs
using Microsoft.AspNetCore.Mvc;
using System.Globalization;

namespace _4d_dotnet.Controllers;

public class WeatherController : Controller
{
    public IActionResult Index()
    {
        var model = new WeatherModel
        {
            MeasurementTime = TimeOnly.FromDateTime(DateTime.Now),
            Instances = new List<WeatherInstance> {
                new WeatherInstance("Wrocław", 28.7, "deszcz"),
                new WeatherInstance("Warszawa", 25.0, "słonecznie"),
                new WeatherInstance("Kraków", 19.9, "pochmurnie"),
                new WeatherInstance("Gdynia", 30.1, "słonecznie"),
            }
        };

        return View(model);
    }

    public IActionResult Request([FromQuery] string city) {

        var weathers = new[] {
            "descz",
            "słońce",
            "zachmurzenie",
            "mgła",
            "przelotny deszcz",
            "lekkie zachmurzenie"
        };

        var instances = Enumerable.Range(0, 6)
            .Select(v => new WeatherRequestInstance(
                CultureInfo.CurrentCulture.DateTimeFormat.DayNames[v],
                Random.Shared.Next(200, 300) / 10m,
                weathers[Random.Shared.Next(0, weathers.Length - 1)]
            ))
            .ToList();

        var model = new WeatherRequestModel(city, instances);

        return View(model);
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - 4d_dotnet</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/_4d_dotnet.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">_4d_dotnet</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Weather" asp-action="Index">Weather</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - 4d_dotnet - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_WeatherInstance.cshtml
@using System.Globalization
@model WeatherInstance

<li>
    <span>@Model.City</span>
    <span>@(Model.Temperature.ToString("#.0", CultureInfo.InvariantCulture))&deg;C</span>
    <span>@Model.Weather</span>
</li>

Views/Weather/Index.cshtml
@using System.Globalization
@model WeatherModel

@{
    ViewData["Title"] = "Weather";
}

<main>
    <h1>Pogoda</h1>
    <h2>Czas pomiaru <strong>@Model.MeasurementTime</strong></h2>

    <ul>
        @foreach(var i in Model.Instances) {
            <partial name="_WeatherInstance" model="i"></partial>
        }
    </ul>

    <form asp-controller="Weather" asp-action="Request" method="GET">
        <label for="city">Miasto</label>
        <input type="text" id="city" name="city">

        <input type="submit" value="Pokaż pogodę">
    </form>

</main>

Views/Weather/Request.cshtml
@using System.Globalization;
@model WeatherRequestModel

@{
    ViewData["Title"] = "Weather";
}

<main>
    <h1>@Model.City</h1>

    <ul>
        @foreach(var i in @Model.Instances) {
            <li>
                <span>@i.Day</span>
                <span>@i.Temperature.ToString("#.0", CultureInfo.InvariantCulture)&deg;C</span>
                <span>@i.Weather</span>
            </li>
        }
    </ul>
</main>